# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf2f47fba0779e390775a96bff4e38539a95452abd6a9be2b177a2eca8500503e74591992cd6896ed8dcae64890fa88e9104c51fb7aa518a29045988f100afd

test:
  secret_key_base: d7c6d90f63491432c9a5e0f8982279d8e5bd4afa0fc6313a3d1ebec93a3a115ed66212729d396982219c39236e727155d840feae350181ef6cce6d1aae67fb14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
